### ISSUE TITLE
Cancel button

### ISSUE THREAD

**Issue by KoenVerbeeck** [Azure-Player/Real-Time-Data-Simulator#4]
There's a big RUN button, but there doesn't seem to be a cancel button. Unless just quitting the entire application counts as cancelling :)

**Comment by NowinskiK** [comment]
Of course - closing the entire application works :)

**Comment by smrroberts** [comment]
@KoenVerbeeck @NowinskiK  - https://github.com/Azure-Player/Real-Time-Data-Simulator/pull/10
